### ISSUE TITLE
Could you please provide the accuracy of the transcription?

### ISSUE THREAD

**Issue by 980202006** [coll-j/drum-transcription#1]

**Comment by coll-j** [comment]
sure, this is actually an outcome of my undergraduate thesis, and I experimented with some models. I will provide a readme with the details of the results as soon as possible. thank you for bringing this up. cheers

**Comment by 980202006** [comment]
Thank you!

**Comment by coll-j** [comment]
@980202006 I updated the readme just now, please do check it out
